"""add ai_summary and ai_summary_generated_at to reports

Revision ID: 3371f08e9309
Revises: cea2c6e67363
Create Date: 2026-07-09 07:00:04.880941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3371f08e9309'
down_revision: Union[str, Sequence[str], None] = 'cea2c6e67363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('frame_detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('frame_index', sa.Integer(), nullable=False),
    sa.Column('damage_type', sa.String(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('bbox', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_frame_det_damage_type', 'frame_detections', ['damage_type'], unique=False)
    op.create_index('idx_frame_det_report_id', 'frame_detections', ['report_id'], unique=False)
    op.create_index(op.f('ix_frame_detections_id'), 'frame_detections', ['id'], unique=False)
    op.create_index(op.f('ix_frame_detections_report_id'), 'frame_detections', ['report_id'], unique=False)
    op.drop_index(op.f('ix_dashboard_preferences_id'), table_name='dashboard_preferences')
    op.drop_index(op.f('ix_dashboard_preferences_user_id'), table_name='dashboard_preferences')
    op.drop_table('dashboard_preferences')
    op.drop_index(op.f('ix_kpi_goals_id'), table_name='kpi_goals')
    op.drop_index(op.f('ix_kpi_goals_metric_key'), table_name='kpi_goals')
    op.drop_table('kpi_goals')
    op.add_column('reports', sa.Column('ai_summary', sa.Text(), nullable=True))
    op.add_column('reports', sa.Column('ai_summary_generated_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('reports', 'capture_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('reports', 'detection_note',
               existing_type=sa.VARCHAR(),
               type_=sa.Text(),
               existing_nullable=True)
    op.drop_index(op.f('idx_report_ai_validation_status'), table_name='reports')
    op.create_index('idx_report_is_hybrid', 'reports', ['is_hybrid'], unique=False)
    op.create_index('idx_report_type', 'reports', ['report_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_report_type', table_name='reports')
    op.drop_index('idx_report_is_hybrid', table_name='reports')
    op.create_index(op.f('idx_report_ai_validation_status'), 'reports', ['ai_validation_status'], unique=False)
    op.alter_column('reports', 'detection_note',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.alter_column('reports', 'capture_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('reports', 'ai_summary_generated_at')
    op.drop_column('reports', 'ai_summary')
    op.create_table('kpi_goals',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('metric_key', sa.VARCHAR(length=64), autoincrement=False, nullable=False),
    sa.Column('label', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('target_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('unit', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('updated_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], name=op.f('kpi_goals_updated_by_fkey'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('kpi_goals_pkey')),
    sa.UniqueConstraint('metric_key', name=op.f('uq_kpi_goal_metric_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_index(op.f('ix_kpi_goals_metric_key'), 'kpi_goals', ['metric_key'], unique=False)
    op.create_index(op.f('ix_kpi_goals_id'), 'kpi_goals', ['id'], unique=False)
    op.create_table('dashboard_preferences',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('widget_order', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('hidden_widgets', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('favorite_widgets', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('dashboard_preferences_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('dashboard_preferences_pkey'))
    )
    op.create_index(op.f('ix_dashboard_preferences_user_id'), 'dashboard_preferences', ['user_id'], unique=True)
    op.create_index(op.f('ix_dashboard_preferences_id'), 'dashboard_preferences', ['id'], unique=False)
    op.drop_index(op.f('ix_frame_detections_report_id'), table_name='frame_detections')
    op.drop_index(op.f('ix_frame_detections_id'), table_name='frame_detections')
    op.drop_index('idx_frame_det_report_id', table_name='frame_detections')
    op.drop_index('idx_frame_det_damage_type', table_name='frame_detections')
    op.drop_table('frame_detections')
    # ### end Alembic commands ###
