"""create all tables

Revision ID: 666068d82849
Revises: 
Create Date: 2026-04-12 09:46:00.068546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '666068d82849'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('profile_picture_url', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('barangay', sa.String(), nullable=True),
    sa.Column('street', sa.String(), nullable=True),
    sa.Column('role', sa.Enum('citizen', 'admin', 'contractor', name='userrole'), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deletion_requested_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target_resource', sa.String(), nullable=True),
    sa.Column('target_id', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('user_agent', sa.String(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_table('cctvs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('location_name', sa.String(), nullable=False),
    sa.Column('barangay', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('stream_url', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.Column('last_maintenance', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_detection_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cctvs_barangay'), 'cctvs', ['barangay'], unique=False)
    op.create_index(op.f('ix_cctvs_id'), 'cctvs', ['id'], unique=False)
    op.create_index(op.f('ix_cctvs_is_active'), 'cctvs', ['is_active'], unique=False)
    op.create_index(op.f('ix_cctvs_latitude'), 'cctvs', ['latitude'], unique=False)
    op.create_index(op.f('ix_cctvs_longitude'), 'cctvs', ['longitude'], unique=False)
    op.create_table('otps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('hashed_code', sa.String(), nullable=False),
    sa.Column('purpose', sa.Enum('email_verify', 'password_reset', 'two_factor', name='otppurpose'), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('attempt_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_otps_email'), 'otps', ['email'], unique=False)
    op.create_index(op.f('ix_otps_expires_at'), 'otps', ['expires_at'], unique=False)
    op.create_index(op.f('ix_otps_id'), 'otps', ['id'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(), nullable=False),
    sa.Column('device_info', sa.String(), nullable=True),
    sa.Column('ip_address', sa.String(), nullable=True),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_hash')
    )
    op.create_index(op.f('ix_refresh_tokens_expires_at'), 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_id'), 'refresh_tokens', ['id'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_is_revoked'), 'refresh_tokens', ['is_revoked'], unique=False)
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('barangay', sa.String(), nullable=True),
    sa.Column('street_name', sa.String(), nullable=True),
    sa.Column('image_url', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('ai_damage_type', sa.Enum('pothole', 'crack', 'none', 'uncertain', name='damagetype'), nullable=True),
    sa.Column('ai_severity', sa.Enum('low', 'critical', name='severitylevel'), nullable=True),
    sa.Column('ai_confidence', sa.Float(), nullable=True),
    sa.Column('is_flagged_fake', sa.Boolean(), nullable=True),
    sa.Column('fake_confidence', sa.Float(), nullable=True),
    sa.Column('is_potential_duplicate', sa.Boolean(), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'VERIFIED', 'DECLINED', 'IN_PROGRESS', 'RESOLVED', name='reportstatus'), nullable=False),
    sa.Column('decline_reason', sa.String(), nullable=True),
    sa.Column('view_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('ai_confidence IS NULL OR (ai_confidence >= 0.0 AND ai_confidence <= 1.0)', name='ck_report_ai_confidence_range'),
    sa.CheckConstraint('fake_confidence >= 0.0 AND fake_confidence <= 1.0', name='ck_report_fake_confidence_range'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['reports.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_ai_damage_type'), 'reports', ['ai_damage_type'], unique=False)
    op.create_index(op.f('ix_reports_ai_severity'), 'reports', ['ai_severity'], unique=False)
    op.create_index(op.f('ix_reports_barangay'), 'reports', ['barangay'], unique=False)
    op.create_index(op.f('ix_reports_created_at'), 'reports', ['created_at'], unique=False)
    op.create_index(op.f('ix_reports_id'), 'reports', ['id'], unique=False)
    op.create_index(op.f('ix_reports_status'), 'reports', ['status'], unique=False)
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('parent_comment_id', sa.Integer(), nullable=True),
    sa.Column('content', sa.String(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['parent_comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_parent_comment_id'), 'comments', ['parent_comment_id'], unique=False)
    op.create_index(op.f('ix_comments_report_id'), 'comments', ['report_id'], unique=False)
    op.create_table('media_attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('media_type', sa.Enum('image', 'video', name='mediatype'), nullable=False),
    sa.Column('is_ai_generated', sa.Boolean(), nullable=True),
    sa.Column('ai_generated_confidence', sa.Float(), nullable=True),
    sa.Column('ai_generated_model_used', sa.String(), nullable=True),
    sa.Column('is_processed', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('ai_generated_confidence >= 0.0 AND ai_generated_confidence <= 1.0', name='ck_media_ai_confidence_range'),
    sa.CheckConstraint('file_size_bytes IS NULL OR file_size_bytes > 0', name='ck_media_file_size_positive'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_media_attachments_id'), 'media_attachments', ['id'], unique=False)
    op.create_index(op.f('ix_media_attachments_report_id'), 'media_attachments', ['report_id'], unique=False)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('info', 'success', 'warning', 'error', name='notificationtype'), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_id'), 'notifications', ['id'], unique=False)
    op.create_index(op.f('ix_notifications_report_id'), 'notifications', ['report_id'], unique=False)
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('projects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('assigned_admin_id', sa.Integer(), nullable=True),
    sa.Column('contractor_id', sa.Integer(), nullable=True),
    sa.Column('priority_level', sa.Enum('LOW', 'HIGH', 'CRITICAL', name='prioritylevel'), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=False),
    sa.Column('estimated_cost', sa.Float(), nullable=True),
    sa.Column('actual_cost', sa.Float(), nullable=True),
    sa.Column('budget_approved', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('estimated_completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_completion_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('actual_cost IS NULL OR actual_cost >= 0', name='ck_project_actual_cost_positive'),
    sa.CheckConstraint('completion_percentage >= 0 AND completion_percentage <= 100', name='ck_project_completion_range'),
    sa.CheckConstraint('estimated_cost IS NULL OR estimated_cost >= 0', name='ck_project_estimated_cost_positive'),
    sa.ForeignKeyConstraint(['assigned_admin_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['contractor_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('report_id')
    )
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.create_index(op.f('ix_projects_priority_level'), 'projects', ['priority_level'], unique=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.create_table('report_upvotes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'report_id', name='uq_user_report_upvote')
    )
    op.create_index(op.f('ix_report_upvotes_id'), 'report_upvotes', ['id'], unique=False)
    op.create_index(op.f('ix_report_upvotes_report_id'), 'report_upvotes', ['report_id'], unique=False)
    op.create_index(op.f('ix_report_upvotes_user_id'), 'report_upvotes', ['user_id'], unique=False)
    op.create_table('ai_detection_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('report_id', sa.Integer(), nullable=False),
    sa.Column('media_attachment_id', sa.Integer(), nullable=True),
    sa.Column('detected_class', sa.Enum('pothole', 'crack', 'none', 'uncertain', name='damagetype'), nullable=False),
    sa.Column('severity', sa.Enum('low', 'critical', name='severitylevel'), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('bounding_boxes', sa.JSON(), nullable=True),
    sa.Column('raw_output', sa.JSON(), nullable=True),
    sa.Column('model_version', sa.String(), nullable=True),
    sa.Column('inference_time_ms', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('confidence >= 0.0 AND confidence <= 1.0', name='ck_ai_confidence_range'),
    sa.CheckConstraint('inference_time_ms IS NULL OR inference_time_ms >= 0', name='ck_ai_inference_time_positive'),
    sa.ForeignKeyConstraint(['media_attachment_id'], ['media_attachments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ai_detection_results_detected_class'), 'ai_detection_results', ['detected_class'], unique=False)
    op.create_index(op.f('ix_ai_detection_results_id'), 'ai_detection_results', ['id'], unique=False)
    op.create_index(op.f('ix_ai_detection_results_media_attachment_id'), 'ai_detection_results', ['media_attachment_id'], unique=False)
    op.create_index(op.f('ix_ai_detection_results_report_id'), 'ai_detection_results', ['report_id'], unique=False)
    op.create_table('project_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('changed_by_id', sa.Integer(), nullable=True),
    sa.Column('old_status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=True),
    sa.Column('new_status', sa.Enum('SCHEDULED', 'IN_PROGRESS', 'ON_HOLD', 'COMPLETED', 'CANCELLED', name='projectstatus'), nullable=True),
    sa.Column('completion_percentage', sa.Float(), nullable=True),
    sa.Column('note', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_updates_created_at'), 'project_updates', ['created_at'], unique=False)
    op.create_index(op.f('ix_project_updates_id'), 'project_updates', ['id'], unique=False)
    op.create_index(op.f('ix_project_updates_project_id'), 'project_updates', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name=op.f('spatial_ref_sys_srid_check')),
    sa.PrimaryKeyConstraint('srid', name=op.f('spatial_ref_sys_pkey'))
    )
    op.drop_index(op.f('ix_project_updates_project_id'), table_name='project_updates')
    op.drop_index(op.f('ix_project_updates_id'), table_name='project_updates')
    op.drop_index(op.f('ix_project_updates_created_at'), table_name='project_updates')
    op.drop_table('project_updates')
    op.drop_index(op.f('ix_ai_detection_results_report_id'), table_name='ai_detection_results')
    op.drop_index(op.f('ix_ai_detection_results_media_attachment_id'), table_name='ai_detection_results')
    op.drop_index(op.f('ix_ai_detection_results_id'), table_name='ai_detection_results')
    op.drop_index(op.f('ix_ai_detection_results_detected_class'), table_name='ai_detection_results')
    op.drop_table('ai_detection_results')
    op.drop_index(op.f('ix_report_upvotes_user_id'), table_name='report_upvotes')
    op.drop_index(op.f('ix_report_upvotes_report_id'), table_name='report_upvotes')
    op.drop_index(op.f('ix_report_upvotes_id'), table_name='report_upvotes')
    op.drop_table('report_upvotes')
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_index(op.f('ix_projects_priority_level'), table_name='projects')
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_report_id'), table_name='notifications')
    op.drop_index(op.f('ix_notifications_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_media_attachments_report_id'), table_name='media_attachments')
    op.drop_index(op.f('ix_media_attachments_id'), table_name='media_attachments')
    op.drop_table('media_attachments')
    op.drop_index(op.f('ix_comments_report_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_parent_comment_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    op.drop_index(op.f('ix_reports_status'), table_name='reports')
    op.drop_index(op.f('ix_reports_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_created_at'), table_name='reports')
    op.drop_index(op.f('ix_reports_barangay'), table_name='reports')
    op.drop_index(op.f('ix_reports_ai_severity'), table_name='reports')
    op.drop_index(op.f('ix_reports_ai_damage_type'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_is_revoked'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_id'), table_name='refresh_tokens')
    op.drop_index(op.f('ix_refresh_tokens_expires_at'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index(op.f('ix_otps_id'), table_name='otps')
    op.drop_index(op.f('ix_otps_expires_at'), table_name='otps')
    op.drop_index(op.f('ix_otps_email'), table_name='otps')
    op.drop_table('otps')
    op.drop_index(op.f('ix_cctvs_longitude'), table_name='cctvs')
    op.drop_index(op.f('ix_cctvs_latitude'), table_name='cctvs')
    op.drop_index(op.f('ix_cctvs_is_active'), table_name='cctvs')
    op.drop_index(op.f('ix_cctvs_id'), table_name='cctvs')
    op.drop_index(op.f('ix_cctvs_barangay'), table_name='cctvs')
    op.drop_table('cctvs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
