"""add assigned_to to reports

Revision ID: cea2c6e67363
Revises: 20260515_2fa_otp_safe
Create Date: 2026-05-15 14:17:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cea2c6e67363'
down_revision: Union[str, None] = '20260515_2fa_otp_safe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # ADD THIS: Add assigned_to column to reports table
    op.add_column('reports', sa.Column('assigned_to', sa.String(length=200), nullable=True))
    
    # NOTE: Do NOT include op.drop_table('spatial_ref_sys') here!
    # That was auto-detected incorrectly by Alembic. PostGIS needs that table.
    
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Drop the column we added
    op.drop_column('reports', 'assigned_to')
    
    # ### end Alembic commands ###